package com.machulski.filler.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.machulski.filler.controller.Constants;
import lombok.Getter;
import lombok.extern.java.Log;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

@Getter
@Log
public class FillerForm {
    private JFrame frame;
    private JPanel panel;
    private JScrollPane scrollPanePreview;
    private JComboBox comboBoxExtension;
    private JButton chooseStartingDirectoryButton;
    private JList directoryList;

    private JEditorPane previewTextPanel = new JEditorPane();
    private ImagePanel previewImagePanel = new ImagePanel(null);

    public FillerForm() {
        frame = new JFrame("Filler");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
    }

    public void reloadPreviewPanel(String panelType) {
        if (Constants.COMBO_BOX_TXT_ELEMENT.equals(panelType))
            scrollPanePreview.setViewportView(previewTextPanel);
        else if (Constants.COMBO_BOX_PNG_ELEMENT.equals(panelType))
            scrollPanePreview.setViewportView(previewImagePanel);
        else
            log.warning("Unsupported panel type");
    }

    private void createUIComponents() {
        directoryList = new JList();
        directoryList.setModel(new DefaultListModel<String>());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.setMinimumSize(new Dimension(800, 600));
        panel.setPreferredSize(new Dimension(800, 600));
        comboBoxExtension = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("*.txt");
        defaultComboBoxModel1.addElement("*.png");
        comboBoxExtension.setModel(defaultComboBoxModel1);
        panel.add(comboBoxExtension, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPanePreview = new JScrollPane();
        panel.add(scrollPanePreview, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPanePreview.setBorder(BorderFactory.createTitledBorder(null, "File Preview", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        chooseStartingDirectoryButton = new JButton();
        chooseStartingDirectoryButton.setText("Choose starting directory");
        panel.add(chooseStartingDirectoryButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(directoryList);
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
